name: spacex_guide
description: SpaceX App made with flutter.

version: 0.2.3+23

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_core:
    git:
      url: git://github.com/asserty308/flutter_packages.git
      path: flutter_core

  flutter_web:
    git:
      url: git://github.com/asserty308/flutter_packages.git
      path: flutter_web

  cupertino_icons: ^1.0.0
  http: ^0.12.2 # call api
  intl: ^0.16.1 # date formatting
  path_provider: ^1.6.24
  # flutter_full_pdf_viewer:
  carousel_slider: ^2.3.1
  flare_flutter: ^2.0.6
  flutter_bloc: ^6.0.6
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.6
  flutter_map: ^0.10.1+1 # TODO Replace
  firebase_messaging: ^7.0.3
  get_it: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.3
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#01233E"
  adaptive_icon_foreground: "assets/app_icon.png"
