name: spacex_guide
description: SpaceX App made with flutter.

version: 0.2.3+23

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_core:
    git:
      url: git://github.com/asserty308/flutter_core.git

  cupertino_icons:
  http: # call api
  intl: # date formatting
  path_provider:
  # flutter_full_pdf_viewer:
  carousel_slider: 
  flare_flutter: # flare animations
  flutter_launcher_icons: # app icon
  flutter_bloc: # state management
  url_launcher:
  webview_flutter:
  flutter_map:
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito:

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#01233E"
  adaptive_icon_foreground: "assets/app_icon.png"
