name: spacex_guide
description: SpaceX App made with flutter.
publish_to: 'none'

version: 0.2.3+23

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_map: ^6.0.1
  get_it: ^7.6.4
  http: ^1.1.0
  intl: ^0.18.1
  latlong2: ^0.9.0
  meta: ^1.8.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.3
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#01233E"
  adaptive_icon_foreground: "assets/app_icon.png"
