name: spacex_guide
description: SpaceX App made with flutter.

version: 0.1.0+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: # ios icons
  http: # calling api
  data_connection_checker: # check network connection
  intl: # date formatting
  flutter_local_notifications: # scheduled notifications
  cached_network_image: # image cache
  path_provider:
  flutter_full_pdf_viewer:
  youtube_player_flutter:
  carousel_slider:
  flare_flutter: # flare animations
  shared_preferences: # simple persistent store
  firebase_core:
  firebase_crashlytics:
  flutter_launcher_icons: # app icon
  flutter_bloc: # state management
  url_launcher:
  webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/RocketLaunch.flr

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#01233E"
  adaptive_icon_foreground: "assets/app_icon.png"